mrtazz/restclient-cpp

include/restclient-cpp/restclient.h, source/restclient.cpp, test/test_restclient_delete.cpp, test/test_restclient_get.cpp, test/test_restclient_post.cpp, test/test_restclient_put.cpp
When one use this lib, he should include the header "restclient.h". If there are some macros which are meaningless for him, it will bother him. For example, he can not define his own VERSION since it already exists in "meta.h"(which is included by restclient.h before). And it will be diffrent to move it to source file(cpp file). 
The reason to move "#include <curl/curl.h>" to source file is similar, there is no namespace in curl/curl.h and it‘s unnecessary for it to appear in restclient.h
=> move two include instructions to source file to avoid macro pollution

source/connection.cc
This fixes the following Valgrind failure:
```
==6158== Conditional jump or move depends on uninitialised value(s)
==6158==    at 0x4738F2: RestClient::Connection::performCurlRequest(std::string const&) (REDACTED)
==6158==    by 0x473D10: RestClient::Connection::get(std::string const&) (REDACTED)
==6158==    by 0x472779: RestClient::get(std::string const&) (REDACTED)
==6158==    by 0x40E59F: RestClientCpp_Http_Test::TestBody() (REDACTED)
==6158==    by 0x447798: void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (REDACTED)
==6158==    by 0x43A2CE: testing::Test::Run() (REDACTED)
==6158==    by 0x43A38C: testing::TestInfo::Run() (REDACTED)
==6158==    by 0x43A4A4: testing::TestCase::Run() (REDACTED) …
```
=> Connection: Initialize timeout and followRedirects

README.md
This fixes 2 problems that I encountered with the example:
1. You need to include `connection.h`.
1. You need a pointer type to handle the `new RestClient...`.
=> README: Update Advanced Example

include/restclient-cpp/restclient.h
This fixes the following warning when compiling with `-Wpedantic`
```
/usr/local/include/restclient-cpp/restclient.h:62:2: warning: extra ‘;’ [-Wpedantic]
};  // namespace RestClient
```
=> Fix -Wpedantic warning

README.md, include/restclient-cpp/connection.h, source/connection.cc, test/test_connection.cc
Add support for limiting the number of redirects. libcurl uses by default -1 which is unlimited. See https://curl.haxx.se/libcurl/c/CURLOPT_MAXREDIRS.html
=> Add support for limiting the number of redirects

.gitignore, README.md, include/restclient-cpp/connection.h, include/restclient-cpp/restclient.h, source/connection.cc, source/restclient.cc, test/test_restclient.cc
Add support for HTTP PATCH and OPTIONS methods for the client. Unfortunately the httpbin does not support OPTIONS method (for now) so the test is disabled.
=> Add PATCH and OPTIONS methods

CMakeLists.txt
Beyond the use of the build system itself this is useful because:
* Other projects using cmake can find and configure themselves to link with this library
* Most IDEs read cmake files in lieu of proprietary project files and properly index
* Dependencies of the project are explicitly stated without compiler-specific syntax
=> Added initial CMakeLists.txt file to match the autotools build.

README.md, include/restclient-cpp/connection.h, source/connection.cc
Added method `RestClient::Connection::SetUnixSocketPath()`, which triggers call to `curl_easy_setopt(foo, CURLOPT_UNIX_SOCKET_PATH, bar)`
Tested with my own project which uses restclient-cpp to connect to Docker over its unix socket ("/var/run/docker.sock") and pull a list of images.
I did not add a unit test because the existing unit tests are not hermetic, and it is a bit complex to stand up an HTTP server on a unix socket (I supposed form/exec nginx would do).
=> Added support for Unix sockets.

autogen.sh
for mac os x hosts "libtoolize" is not a correct command.
this is because mac bundles it's own version of "libtool",
which works differently, and may not even exist.
instead if you use brew to install libtool: `brew install libtool`
on mac, it writes to: `glibtoolize` as to leave mac happy with
it's own version of libtool by default.
this commit will properly use glibtoolize if detected, otherwise
will fallback to just using libtoolize.
=> mac os x uses glibtoolize not libtoolize

CMakeLists.txt, Makefile.am, include/restclient-cpp/helpers.h, test/test_helpers.cc
ptr_fun was deprecated in C++11, and removed in C++17. lambdas
have also been around since C++11. so there should be no loss in
supported targets, but also adds in support for C++17 and beyond.
=> use lambda's over ptr_fun

CMakeLists.txt
HOMEPAGE_URL in project() needs 3.12.
[3.11](https://cmake.org/cmake/help/v3.11/command/project.html) vs.  [3.12](https://cmake.org/cmake/help/v3.12/command/project.html)
=> Set minimum CMake version to 3.12.0

CMakeLists.txt
GNUInstallDirs are portable, many users are familiar with them and they make the
life of package maintainers easier.
----
GNUInstallDirs is available in 3.10:
<https://cmake.org/cmake/help/v3.10/module/GNUInstallDirs.html>.
Linux distributions usually have profiles for CMake that set these directories
to the right locations. This change will make packaging easier.
I have left the old variables intact for backwards compatibility.
=> Replace hardcoded installation directories with GNUInstallDirs.

CMakeLists.txt
Use find_dependency() to depend on CURL and Threads so CMake users don't have to
do it themselves.
----
* `CMakeFindDependencyMacro` and `find_dependency()` are available in 3.10:
<https://cmake.org/cmake/help/v3.10/module/CMakeFindDependencyMacro.html>.
* `FindCurl` is available in 3.10:
<https://cmake.org/cmake/help/v3.10/module/FindCURL.html>.
* `FindThreads` is available in 3.10:
<https://cmake.org/cmake/help/v3.10/module/FindThreads.html>.
Since curl and threads are not optional, they should be required by
`restclient-cppConfig.cmake`, in my opinion. It makes the CMakeLists.txt of
users a bit cleaner and shorter and has no downsides, as far as I'm …
=> Add CURL and Threads as dependency in CMake config.

CMakeLists.txt
`COMPILE_TYPE` is left in for backwards compatibility.
----
`BUILD_SHARED_LIBS` is availbale in CMake 3.10:
<https://cmake.org/cmake/help/v3.10/variable/BUILD_SHARED_LIBS.html>
Will make life easier for package maintainers and CMake users who already know
about that flag immediately recognize it's function.
=> Use the standard CMake-flag BUILD_SHARED_LIBS.

README.md, include/restclient-cpp/connection.h, source/connection.cc, test/test_connection.cc
=> Added support for progress reporting when downloading/uploading

Makefile.am, README.md, include/restclient-cpp/connection.h, source/connection.cc, test/squid.conf, test/test_connection.cc, test/test_restclient.cc, test/tests.cpp, test/tests.h
1. Allow write callback.  Application was to use it to leverage the Kubernetes watch API which maintains a long-running connection.
1. API to terminate connection from another thread.
1. Fix all the disabled/broken CI tests that block the merge.
- #162 write callback support
- #161 CI does not work locally
=> write callback and termination API

CMakeLists.txt
Headers to be available when making use of the `add_subdirectory` from a
parent project.
This will allow other `add_subdirectory`'s to reference the headers during
the build process of cmake within `target_include_directories`.
This would make issues like #130 easier to do for cmake users.
This change also moves the file towards CMake standards.
I can give a more detailed explanation if needed. I can do more cleanup if needed as well.
I noticed there aren't tests for installation of files, not sure if that is something interested in or expected. Can do if needed for idempotent issues for changes like this.
=> These two lines allow the scope of the property <target> for the public

include/restclient-cpp/connection.h, source/connection.cc, test/test_connection.cc
#166 
There should be a way to disable SSL verification to authenticate with bearer tokens.
Something like this would do:
```
// set a non-existing file for the CA file, should allow access anyway
conn->SetCAInfoFilePath("non-existent file");
conn->SetVerifyPeer(false);
RestClient::Response res = conn->get("/get");
EXPECT_EQ(200, res.code);
```
=> Allow SSL peer verification to be disabled.

README.md
Added Instructions to help build with Mingw64. This would help people build the library under mingw64 and msys2 toolchains.
=> Added Mingw Instructions

include/restclient-cpp/connection.h
The previous code did not compile under GCC-13 because libstdcpp
headers have changed such that cstdint is not included implicitly.
Add cstdint include when `uint64_t` types are used.
Signed-off-by: Patrick Williams <patrick@stwcx.xyz>
=> Fix missing cstdint include

include/restclient-cpp/connection.h
**DESCRIPTION**
The PR is intended to address the the issue as noted in https://github.com/mrtazz/restclient-cpp/issues/173 where Valgrind has raised a potential issue due to the fact that the `curlErrorBuf` has not be explicitly initialised.  
The change simply initialises this array at compile time.
**REFS**
- [Original Issue](https://github.com/mrtazz/restclient-cpp/issues/173)
**CHECKLIST**
=> init Connection::curlErrorBuf[] at compile

docs/index.md
If it's not `application/json`, some servers will not parse it properly into json (as in my case, the nodejs express.json() middleware)
=> [docs] use correct json mime type in example

CHANGELOG.md, CMakeLists.txt, Makefile.am, configure.ac
closes https://github.com/mrtazz/restclient-cpp/issues/192
=> bump to version 0.5.3
